name: nocode
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_design:
    # path: ../../flutter_design
  flutter_design_viewer:
    # path: ../
  # icon
  flutter_feather_icons: ^2.0.0+1
  ionicons: ^0.1.2
  # system
  url_strategy: ^0.2.0
  # framework
  flutter_hooks: ^0.18.2
  # state management
  hooks_riverpod: ^1.0.3
  # control
  flutter_staggered_grid_view: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_design_codegen: ^0.0.11-pre+1
  flutter_design_codegen:
    # path: ../../flutter_design_codegen
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
